# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Xian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Province'),
        ),
    ]
