# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20161208_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_to_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='a_to_b',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author'),
        ),
        migrations.AddField(
            model_name='a_to_b',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Book'),
        ),
    ]
