# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20161212_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_to_b',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='a_to_b',
            name='bid',
        ),
        migrations.DeleteModel(
            name='A_to_B',
        ),
    ]
