# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20161212_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='m',
            field=models.ManyToManyField(to='app01.Book'),
        ),
    ]
