# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_userprofile_stu_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_fuck_him_to_death', '弄死小虎逼'),)},
        ),
    ]
